spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/hrs?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:EastWind}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
server.port=${PORT:8081}
server.error.include-message=always
